### PR TITLE
Update `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**
This is for the future.

### CODE REVIEW

**Comment by zaeonNineZero** [comment]
Thanks again! I'll merge the new translations right away and include them in the v1.4.0 ports to other MC versions. I plan on pushing this out to the 1.19.2 branch alongside more updated translations (including updated Japanese and Korean localization). I'll label that patch as 'v1.4.1'.

**Comment by mpustovoi** [comment]
Great!
A quick question: was that you who made the unofficial port of MrCrayfish's Gun Mod on 1.20.1 I found it in the depths of GitHub? it also had some guns that I don't remember in the original mod. 🤔

**Comment by mpustovoi** [comment]
If it was you, then I'm very grateful to you for that. Now I can't switch to another Gun Mod port. 😅 (that one that has a page on curseforge)

**Comment by chemlzh** [comment]
> Great! A quick question: was that you who made the unofficial port of MrCrayfish's Gun Mod on 1.20.1 I found it in the depths of GitHub? it also had some guns that I don't remember in the original mod. 🤔

Nope. The unofficial port was made by [MikhailTapio](https://github.com/MikhailTapio), a Chinese modder.

Here is the introduction page on MCMod: https://www.mcmod.cn/class/12928.html

And here is the source code: https://github.com/MikhailTapio/MrCrayfishGunMod

As for source code in ZaeonNineZero, it has said that it's just for testing.

image

**Comment by mpustovoi** [comment]
Is that the same port?
https://github.com/MrCrayfish/MrCrayfishGunMod/pull/505#issuecomment-1815034739

**Comment by chemlzh** [comment]
> Is that the same port? [MrCrayfish/MrCrayfishGunMod#505 (comment)](https://github.com/MrCrayfish/MrCrayfishGunMod/pull/505#issuecomment-1815034739)

Nope, is seems that some other modders push another 1.20.1 port. But [MikhailTapio](https://github.com/MikhailTapio) did push his own 1.20.1 port to original CGM. Both of 1.20.1 ports have not been accepted.

https://github.com/MrCrayfish/MrCrayfishGunMod/pull/520

**Comment by mpustovoi** [comment]
Well, I hope that MrCrayfish will eventually return to work on the Gun mod.

**Comment by mpustovoi** [comment]
Although, looking at the [Framework updates](https://www.curseforge.com/minecraft/mc-mods/framework/files/all?page=1&pageSize=20), it seems that MrCrayfish may skip 1.20.1 and target 1.20.4 right away.
Unfortunately, mods such as Farmer's Delight, etc., haven't yet been ported to 1.20.4.

**Pull request merged**
