### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Updated ru_ru.json

### CODE REVIEW

**Comment by mpustovoi** [comment]
Also, thank you for the early port of Gun Mod on 1.20.1

**Comment by zaeonNineZero** [comment]
Thank you for the updated translations! I'll include them in the next update, which will either be v1.3.3 or v1.4.0.

**Comment by zaeonNineZero** [comment]
A little heads up, I've added some new items to the mod that need translations. Can you update ru_ru.json to add translations for these items? Thank you again for your work in translating the mod.

**Comment by mpustovoi** [comment]
Done.

**Comment by zaeonNineZero** [comment]
Looks good to me. Again, thank you for the help!

**Pull request merged**
